### ISSUE TITLE
Incorrect 5.4.0 tag

### ISSUE THREAD

**Issue by defagos** [CommandersAct/iOSV5#10]
Hi,

The 5.4.0 tag recently created has been attached to the wrong commit. As a result SPM pulls 5.3.3 ServerSide binaries when pointing at the 5.4.0 tag.

![Screenshot 2023-09-28 at 08 47 31](https://github.com/CommandersAct/iOSV5/assets/170201/a6d53860-6196-4a67-a245-62bb02d0d7ac)

Could you please move the tag to a more recent commit on `master`, possibly `0c61738eb162debc46939da10687227ef836245d`? Thank you very much in advance.

**Comment by CommandersAct** [comment]
Ouch that's a horrible fail :( 
Sorry about that, we released a new package swift 5.4.1

**Comment by defagos** [comment]
Thanks for the newly released tag (though I guess you chose to still deliver 5.4.0 binaries on purpose, not to move the existing tag).

I will close this issue.
