### ISSUE TITLE
Wrong device language value in version 5.4.1

### ISSUE THREAD

**Issue by pyby** [CommandersAct/iOSV5#11]
Following the Android SDK issue https://github.com/CommandersAct/AndroidV5/issues/5, we did test again on the iOS SDK.

- Set a device in `en-US`.
- Run an application with only `fr` language and region.

Current result:
- `context.device.language` = fr
- `context.device.region` = US

Expected result:
- `context.device.language` = en
- `context.device.region` = US

Could it be fixed for `context.device`? Maybe around `NSLocale.preferredLanguages`.

Current iOS SDK returns language value which looks for `context.app.language` property.

**Comment by CommandersAct** [comment]
Should be fixed in 5.4.1 released this morning!

**Comment by pyby** [comment]
@CommandersAct  thanks a lot.
Because of https://github.com/CommandersAct/iOSV5/issues/10, it's 5.4.2 for iOS :)
Maybe align patch version on both Android and iOS next time, if you like versioning.

Tested successfully on iOS.
