### ISSUE TITLE
Missing custom data variables in Event after .waitForUserAgent()

### ISSUE THREAD

**Issue by Hekod** [CommandersAct/iOSV5#12]
This issue might be related to https://github.com/CommandersAct/iOSV5/issues/8

I just re-tested this with the latest SDK version (TCConsent 5.1.8, TCCore 5.3.0, TCServerSide 5.4.0) and I still have problems with ServerSide's ".waitForUserAgent()" call.

If I send an event quickly after the call of ".waitForUserAgent()", then this event is delayed correctly until the user agent is known. However, all custom data attributes are missing in the event when it is actually sent.

Could you please look at this again?

**Comment by CommandersAct** [comment]
Hello !
We'll check as soon as possible we have a lot of subjects currently so probably at the end of the week

**Comment by ahakimsaid** [comment]
Hello @Hekod, 

I was able to reproduce and understand what was going. the issue has been fixed and will be part of the upcoming release.

Thanks for reporting it!

**Comment by Hekod** [comment]
Hi @ahakimsaid,
is there already a plan for when the fix will be released?
Thank you

**Comment by ahakimsaid** [comment]
Hi @Hekod, 

the fix was released on [TCCore 5.3.2](https://github.com/CommandersAct/iOSV5/releases/tag/5.4.3)
