### ISSUE TITLE
Apple Privacy Manifest File

### ISSUE THREAD

**Issue by mattiacantalu** [CommandersAct/iOSV5#15]
> Third-party software development kits (SDKs) can provide great functionality for apps; they can also have the potential to impact user privacy in ways that aren’t obvious to developers and users. As a reminder, when you use a third-party SDK with your app, you are responsible for all the code the SDK includes in your app, and need to be aware of its data collection and use practices [...]

> [Privacy manifest files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests) outline the privacy practices of the third-party code in an app, in a single standard format. When you prepare to distribute your app, Xcode will combine the privacy manifests across all the third-party SDKs used by your app into a single, easy-to-use report. With one comprehensive report that summarizes all the third-party SDKs found in an app, it will be even easier for you to create more accurate Privacy Nutrition Labels.

> Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. 

Any update about the [privacy manifest file](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)?

**Comment by CommandersAct** [comment]
Hello !
We are aware that we will need to provide a manifest soon but we didn't have time to do so yet.
In my knowledge we're using 2 categories:

NSPrivacyCollectedDataTypeDeviceID since the userID we're collecting is actually not really linked to the user but generated for the device

And everything else we're collecting seems to fall in this default category: NSPrivacyCollectedDataTypeOtherDataTypes.

We'll update the SDK with those as soon as possible.

**Comment by mattiacantalu** [comment]
Added in https://github.com/CommandersAct/iOSV5/releases/tag/5.4.6

**Comment by mattiacantalu** [comment]
Ehi @CommandersAct are you aware about this warning in latest release?

> ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/TCConsent.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, keys and values in your app’s privacy manifest must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by CommandersAct** [comment]
Hello !
I wasn't aware I'll check what can be done.
I should probably remove the tracking url since it's not a tracking done for advertising and that the only things Apple cares about.

**Comment by clementleroy** [comment]
Do you have an ETA on this issue ? Apple is now refusing our app submission due to this error.

**Comment by SudhirKaushik** [comment]
yes same here. Can you please take this on Priority and provide a release ASAP?

**Comment by CommandersAct** [comment]
It is of course our most urgent priority.

**Comment by CommandersAct** [comment]
TCConsent 5.3.1 removed the problematic URL and should work.
