### ISSUE TITLE
Failed to fetch podspec

### ISSUE THREAD

**Issue by aliabbas90** [CommandersAct/iOSV5#3]
Since this morning, we have been facing an issue while trying to install the v5 of TC. Both links `https://raw.githubusercontent.com/TagCommander/iOSV5/master/TCCore/latest-TCCore.podspec` and 
`https://raw.githubusercontent.com/TagCommander/iOSV5/master/TCServerSide/latest-TCServerSide.podspec` aren't available anymore (error 404).

**Comment by aliabbas90** [comment]
Following the answer from CommanderActs, the new links are: 

 ```
pod 'latest_TCCore', :podspec => 'https://raw.githubusercontent.com/TagCommander/iOSV5/master/TCCore/latest_TCCore.podspec'
pod 'latest_TCServerSide', :podspec => 'https://raw.githubusercontent.com/TagCommander/iOSV5/master/TCServerSide/latest_TCServerSide.podspec'
```

**Comment by CommandersAct** [comment]
We are sorry for the inconvenience we renamed everything to respect swift package manager and this was a side effect we didn't realise.
