### ISSUE TITLE
SPM integration with version 5.2.2 failed with 2 checksum issues 

### ISSUE THREAD

**Issue by pyby** [CommandersAct/iOSV5#4]
In a iOS and tvOS project, we use the SPM integration.

15.12.2022: the decency updated to release "5.2.2":

```
dependencies: [
  .package(name: "TagCommander", url: "https://github.com/CommandersAct/iOSV5.git", .upToNextMinor(from: "5.2.2"))`
]
```

Last build on our CI was on 09.01.2023.

Building again on 24.03.2023, the SPM has two errors in logs:

> checksum of downloaded artifact of binary target 'TCPartners' (92d22dd3eff72dd6019d1cdf8907ab15ade6a3aaadf74d3498b34c9dea992d32) does not match checksum specified by the manifest (b8bb9adb15aaf44a5f1406584c05396f2bad7bc481941d38b9f0a583efd58b08)
> checksum of downloaded artifact of binary target 'TCIAB' (9bb5498e7572c5fe44b217a5b4110189000a18e9831aafbdf7a0bdb34a36e459) does not match checksum specified by the manifest (fab7b1b6d4fcc87457763c172fa28c4d5f26f1e6fed3248ee73729b280cb969d)

From the `Package.swift`file:
- `TCPartners` has checksum `b8bb9adb15aaf44a5f1406584c05396f2bad7bc481941d38b9f0a583efd58b08`.
- `TCIAB` has checksum `fab7b1b6d4fcc87457763c172fa28c4d5f26f1e6fed3248ee73729b280cb969d`.

But after downloading the related zip files:
- https://github.com/CommandersAct/iOSV5/raw/master/TCPartners/5/0/1/TCPartners.zip has now checksum: `92d22dd3eff72dd6019d1cdf8907ab15ade6a3aaadf74d3498b34c9dea992d32`.
- https://github.com/CommandersAct/iOSV5/raw/master/TCIAB/5/0/1/TCIAB.zip has now checksum: `9bb5498e7572c5fe44b217a5b4110189000a18e9831aafbdf7a0bdb34a36e459`.

The SPM resolutions failed and sadly, the project can't compile anymore.

It seems that binaries were updated with a different binaries in.

Maybe a fix could be done if you found the previous zip files.

**Comment by cyrillelegrand** [comment]
Same here. Cannot compile my project anymore, even when I manually set it to a fixed, previous version.

**Comment by CommandersAct** [comment]
Hello, 
Thanks for reaching out. 
We are sorry to hear that, the problem has been identified and our team is working on a new release ASAP.
Expect a new release this morning. 

Cheers,

**Comment by CommandersAct** [comment]
Old binaries for TCIAB and TCPartners are restored. 
release 5.3.0 was re-pushed, you may need to reset your swift package manager cache if you wanna be on the latest version. 

++

**Comment by cyrillelegrand** [comment]
It's working fine now. Many thanks!

**Comment by CommandersAct** [comment]
We're changing our release scripts so that it won't happen again. Sorry for the inconvenience.

**Comment by pyby** [comment]
@CommandersAct .
21.04.2023: Again a checksum issue:

```
Showing All Issues
checksum of downloaded artifact of binary target 'TCIAB' (6d709f893b993249571e04cc4bae59e3b554fa49ad047a85640a6937b7e6a3dd) does not match checksum specified by the manifest (fab7b1b6d4fcc87457763c172fa28c4d5f26f1e6fed3248ee73729b280cb969d)
```

I confirmed that currently: https://github.com/CommandersAct/iOSV5/raw/master/TCIAB/5/0/1/TCIAB.zip
The zip checksum is `6d709f893b993249571e04cc4bae59e3b554fa49ad047a85640a6937b7e6a3dd`.

I can't reopen this issue.

**Comment by CommandersAct** [comment]
Even using the new release? I haven't touch IAB since then.
I know my script update the generated files and that it was an issue with checksum for the previous releases, but the 5.3.1 should work :(

**Comment by pyby** [comment]
It in the roadmap. @defagos mentioned the new conflit with `event_name` property, last checkbox in the related issue. that why it takes time :)
https://github.com/SRGSSR/srganalytics-apple/issues/62

Thanks for answer.

**Comment by pyby** [comment]
I don't know it it was fixed.
But we migrated to the new 5.3.1.

I close the issue for now.
