### ISSUE TITLE
Incorrect SPM binary checksums

### ISSUE THREAD

**Issue by defagos** [CommandersAct/iOSV5#6]
# Description of the problem

A series of commits were recently made on `master` for delivery of version 5.3.1. Sadly, due to how the SPM package manifest has been created (pointing at binaries on `master` which can be updated by mistake), now attempting to add version 5.3.0, which was previously possible, fails with a checksum error:

![Screenshot 2023-04-20 at 15 51 21](https://user-images.githubusercontent.com/170201/233388008-9d319875-82e9-4ce6-a43a-66908ed409fe.jpg)

As a result none of our projects using version 5.3.0 of the Commanders Act SDK now compile, which is a bit annoying to say the least. We would be thankful if you could fix this issue so that we can continue our work without having to revert to version 5.2.1.

# How to reproduce

1. Create a new Xcode project.
2. Add `https://github.com/CommandersAct/iOSV5.git` as package dependency for the tag 5.3.0. Package resolution fails with the above error.

# Expected behavior

Integration with SPM of any version of Commanders Act is possible and reliable.

# Actual behavior

Integration with SPM of version 5.3.0 fails with a checksum error.

# Advice

SPM binaries are currently retrieved from the `master` branch as declared in the [Swift package manifest](https://github.com/CommandersAct/iOSV5/blob/master/Package.swift). This is probably a bad idea as these binaries can be inadvertently updated, thus changing their checksum, creating a potential mismatch with the package manifest.

A possible solution is to use assets associated with GitHub releases, as [we did in the past](https://github.com/SRGSSR/TCServerSide-xcframework-apple/releases) while Commanders Act did not support SPM officially. Another approach is likely to have the package manifest file URLs not point at `master`, but rather at the associated tag directly.

**Comment by CommandersAct** [comment]
Hello !
Yes there is a known issue on this, I thought we corrected it last week but we made a mistake somewhere and the one who did everything is in holiday :(

I'll try my best to fix everything as soon as possible.

**Comment by defagos** [comment]
No worries, thanks for the quick answer. In the meantime I will fork the repository and remove recent commits. I will then use the fork as dependency. This way we'll be able to build our project again.

**Comment by defagos** [comment]
Thank you very much for the quick fix you made. We could switch back to the official repository.
