### ISSUE TITLE
Disable verbose logging by default

### ISSUE THREAD

**Issue by defagos** [CommandersAct/iOSV5#7]
# Description of the problem

The Commanders Act SDK logs events to the console by default. This should rather be an opt-in as it distracts from more relevant logging developers might need for their work.

# How to reproduce

Integrate the Commanders Act SDK (e.g. version 5.3.0+) as documented and observe the Xcode console when events are sent. Event payloads are logged to the console, cluttering the output.

# Expected behavior

Verbose logging is disabled by default.

# Actual behavior

Verbose logging is enabled by default.

# Workaround

Calling `TCDebug.setDebugLevel(TCLogLevel_None)` before instantiating a `ServerSide` makes it possible to inhibit verbose logging, including the one from the startup phase (site identifier, SDK version, etc.).

**Comment by CommandersAct** [comment]
Acknowledged !
We modified the code it will be added to a later release :)

**Comment by defagos** [comment]
Fantastic, thank you very much for this improvement. Feel free to close this issue.
