### ISSUE TITLE
waitForUserAgent breaks request JSON and results in Error

### ISSUE THREAD

**Issue by Hekod** [CommandersAct/iOSV5#8]
Calling ServerSide's ".waitForUserAgent()" results in a broken JSON request to https://collect.commander1.com/events...

It seems like the user-agent is added to the end of the json-string which is not parsable anymore after that

example:
`{...}&TC_USER_AGENT=Mozilla%2F5.0%20%28iPhone%3B%20CPU%20iPhone%20OS%2016_2%20like%20Mac%20OS%20X%29%20AppleWebKit%2F605.1.15%20%28KHTML%2C%20like%20Gecko%29%20Mobile%2F15E148`

result is status 400 with "Unexpected token & in JSON at position 1891"

**Comment by CommandersAct** [comment]
Hi @Hekod, 

Thank you for reaching out, 
it seems like a bug that affect some of the pending events before the user agent is available.

A fix was made and will be published with the next release.
