### ISSUE TITLE
Missing device language in V5 

### ISSUE THREAD

**Issue by pyby** [CommandersAct/iOSV5#9]
We got a report from data engineers that SDK v4 sent: `TC_LANGUAGE`: the device’s language and location (ex: “fr_FR”)
https://community.commandersact.com/tagcommander/getting-started/setup-guides/ios#step-1-defining-the-applications-tagging-plan

In fact:

Property | language
-- | --
TC_LANGUAGE | en_US
TC_LANGUAGE_CS | en
TC_LANGUAGE_GA | en-US

SDK V5, the `device` object does not have any language property.
https://doc.commandersact.com/developers/tracking/about-events/mobile-sdk-event-specificity#context-greater-than-device-greater-than-os

Are there any plans to add these properties in a future version for iOS and Android, or should application add those properties itself?

**Comment by CommandersAct** [comment]
Hello !
It seems to be missing indeed and I'm not sure why we removed those.

We will add device->language ('en' in this case) and device->region ('US' in this example)
Afterwards they can be combined inside the interface if needed.

We will probably release it this week among other changes.

**Comment by CommandersAct** [comment]
It's Released :)
TCCore 5.3.0, TCServerSide 5.4.0

**Comment by pyby** [comment]
@CommandersAct Thanks for quick update.
Sorry, I didn't take time to create a similar issue for Android SDK. https://github.com/CommandersAct/AndroidV5/commits/master

Should I create an issue as well? I can.

**Comment by CommandersAct** [comment]
I updated Android and iOS at the same time so it should be ok

**Comment by pyby** [comment]
Better release notes on iOS GitHub repository.
Ok, thank you for the shared information.

We'll get back to you feedback is any issue.
